/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parking;

import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Estefania
 */
public class Introducir extends javax.swing.JFrame {

    /**
     * Creates new form Introducir
     *
     * @param aparcamiento
     */
    Aparcamiento aparcamiento;

    public Introducir(Aparcamiento aparcamiento) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.aparcamiento = aparcamiento;

        ClaseVehiculo.removeAllItems();
        ClaseVehiculo.addItem("Turismo ");
        ClaseVehiculo.addItem("Todoterreno");
        ClaseVehiculo.addItem("Furgoneta");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Atras = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        TipoVehiculo = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        ClaseVehiculo = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        Abono = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        EscribirMatricula = new javax.swing.JTextArea();
        Aceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        Atras.setBackground(new java.awt.Color(255, 153, 153));
        Atras.setForeground(new java.awt.Color(255, 51, 51));
        Atras.setIcon(new javax.swing.ImageIcon("C:\\Users\\admi\\Dropbox\\Universidad\\Segundo Semestre\\Progamacion\\Laboratorio\\PEC2\\Parking\\Gifs ANimados Flechas (178).GIF")); // NOI18N
        Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasActionPerformed(evt);
            }
        });

        jLabel2.setText("Tipo de vehículo");

        TipoVehiculo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Automóvil", "Camión" }));
        TipoVehiculo.setName("tipovehiculo"); // NOI18N
        TipoVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoVehiculoActionPerformed(evt);
            }
        });

        jLabel3.setText("Clase");

        ClaseVehiculo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Turismo", "Todoterreno", "Furgoneta", "Menos de 3 ejes", "Más de 3 ejes", "" }));
        ClaseVehiculo.setToolTipText("");
        ClaseVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClaseVehiculoActionPerformed(evt);
            }
        });

        jLabel4.setText("Vehiculo con abono");

        Abono.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Abono", "No abono", " " }));
        Abono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbonoActionPerformed(evt);
            }
        });

        jLabel5.setText("Escriba la matricula de su vehículo");

        EscribirMatricula.setColumns(20);
        EscribirMatricula.setRows(5);
        jScrollPane1.setViewportView(EscribirMatricula);

        Aceptar.setText("Aceptar");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ClaseVehiculo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TipoVehiculo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Abono, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                .addGap(0, 167, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Atras, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Aceptar)
                .addGap(39, 39, 39))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Atras)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TipoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClaseVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Abono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 259, Short.MAX_VALUE)
                .addComponent(Aceptar)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasActionPerformed
        VentanaDeBienvenida atras = new VentanaDeBienvenida();
        atras.setVisible(true);
        Introducir.this.dispose();
    }//GEN-LAST:event_AtrasActionPerformed

    private void ClaseVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClaseVehiculoActionPerformed

    }//GEN-LAST:event_ClaseVehiculoActionPerformed

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed

        try {

            String tipoVehiculo = TipoVehiculo.getSelectedItem().toString();

            switch (tipoVehiculo) {
                case "Automóvil":
                    Automovil coche = new Automovil();

                    if (Abono.getSelectedItem().toString() == "Abono") {
                        coche.setAbono(true);
                    } else {
                        coche.setAbono(false);
                    }
                    coche.setMatricula(EscribirMatricula.getText());
                    coche.setEntrada(Calendar.getInstance().getTime());
                    coche.setTipo(ClaseVehiculo.getSelectedItem().toString());

                    aparcamiento.introducirVehiculo(coche);

                    break;
                case "Camión":
                    Camion truck = new Camion();

                    if (Abono.getSelectedItem().toString() == "Abono") {
                        truck.setAbono(true);
                    } else {
                        truck.setAbono(false);
                    }
                    truck.setMatricula(EscribirMatricula.getText());
                    truck.setEntrada(Calendar.getInstance().getTime());
                    truck.setEjes(ClaseVehiculo.getSelectedItem().toString());

                    aparcamiento.introducirVehiculo(truck);
                    break;
            }

        } catch (AparcamientoException ex) {
            Logger.getLogger(Introducir.class.getName()).log(Level.SEVERE, null, ex);
        }
        VentanaDeBienvenida atras = new VentanaDeBienvenida();
        atras.setVisible(true);
        Introducir.this.dispose();
    }//GEN-LAST:event_AceptarActionPerformed

    private void TipoVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoVehiculoActionPerformed

        String tipoVehiculo = TipoVehiculo.getSelectedItem().toString();

        switch (tipoVehiculo) {
            case "Automóvil":
                ClaseVehiculo.removeAllItems();
                ClaseVehiculo.addItem("Turismo ");
                ClaseVehiculo.addItem("Todoterreno");
                ClaseVehiculo.addItem("Furgoneta");

                break;
            case "Camión":
                ClaseVehiculo.removeAllItems();
                ClaseVehiculo.addItem("Menos de 3 ejes");
                ClaseVehiculo.addItem("Más de 3 ejes");
                break;
        }
    }//GEN-LAST:event_TipoVehiculoActionPerformed

    private void AbonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AbonoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Abono;
    private javax.swing.JButton Aceptar;
    private javax.swing.JButton Atras;
    private javax.swing.JComboBox ClaseVehiculo;
    private javax.swing.JTextArea EscribirMatricula;
    private javax.swing.JComboBox TipoVehiculo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
