
import java.io.IOException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


public class AñadirTexto extends javax.swing.JFrame {

    /**
     * Creates new form AñadirTexto
     */
    private VentanaBienvenida parent;

    public AñadirTexto(VentanaBienvenida ett) {
        initComponents();
        PrimariaCajita.setSelected(true);
        PrimeroCajita.setSelected(true);
        PrimariaCajita.setEnabled(false);
        PrimeroCajita.setEnabled(false);

        parent = ett;
        parent.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AutorCampo = new javax.swing.JTextField();
        EditorialCampo = new javax.swing.JTextField();
        AñadirDiccionarioBoton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        IsbnCampo = new javax.swing.JTextField();
        TituloCampo = new javax.swing.JTextField();
        PrimariaCajita = new javax.swing.JCheckBox();
        EsoCajita = new javax.swing.JCheckBox();
        BachCajita = new javax.swing.JCheckBox();
        PrimeroCajita = new javax.swing.JRadioButton();
        SegundoCajita = new javax.swing.JRadioButton();
        TerceroCajita = new javax.swing.JRadioButton();
        CuartoCajita = new javax.swing.JRadioButton();
        QuintoCajita = new javax.swing.JRadioButton();
        SextoCajita = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        MateriaCampo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        PrecioVenta = new javax.swing.JSlider();
        PrecioConsulta = new javax.swing.JSlider();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LIBRERIA DIGITAL");

        AñadirDiccionarioBoton.setText("Terminar");
        AñadirDiccionarioBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñadirDiccionarioBotonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("ISBN:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Titulo:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Autor:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Curso recomendado:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Editorial:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Precio de venta:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Precio de consulta mensual:");

        PrimariaCajita.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        PrimariaCajita.setText("Primaria");
        PrimariaCajita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrimariaCajitaActionPerformed(evt);
            }
        });

        EsoCajita.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        EsoCajita.setText("ESO");
        EsoCajita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EsoCajitaActionPerformed(evt);
            }
        });

        BachCajita.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BachCajita.setText("BACH");
        BachCajita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BachCajitaActionPerformed(evt);
            }
        });

        PrimeroCajita.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        PrimeroCajita.setText("1º");
        PrimeroCajita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrimeroCajitaActionPerformed(evt);
            }
        });

        SegundoCajita.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        SegundoCajita.setText("2º");
        SegundoCajita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SegundoCajitaActionPerformed(evt);
            }
        });

        TerceroCajita.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TerceroCajita.setText("3º");
        TerceroCajita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TerceroCajitaActionPerformed(evt);
            }
        });

        CuartoCajita.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        CuartoCajita.setText("4º");
        CuartoCajita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuartoCajitaActionPerformed(evt);
            }
        });

        QuintoCajita.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        QuintoCajita.setText("5º");
        QuintoCajita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuintoCajitaActionPerformed(evt);
            }
        });

        SextoCajita.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        SextoCajita.setText("6º");
        SextoCajita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SextoCajitaActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Materia:");

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        PrecioVenta.setMajorTickSpacing(2);
        PrecioVenta.setMaximum(30);
        PrecioVenta.setMinimum(10);
        PrecioVenta.setPaintLabels(true);
        PrecioVenta.setPaintTicks(true);

        PrecioConsulta.setMajorTickSpacing(1);
        PrecioConsulta.setMaximum(10);
        PrecioConsulta.setMinimum(1);
        PrecioConsulta.setPaintLabels(true);
        PrecioConsulta.setPaintTicks(true);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("AÑADIR NUEVO LIBRO DE TEXTO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jLabel9)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(AutorCampo)
                                            .addComponent(TituloCampo)
                                            .addComponent(IsbnCampo)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(EditorialCampo))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(PrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(PrecioConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(45, 45, 45))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(MateriaCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(PrimariaCajita)
                                            .addComponent(PrimeroCajita)
                                            .addComponent(CuartoCajita))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(EsoCajita)
                                            .addComponent(SegundoCajita)
                                            .addComponent(QuintoCajita))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(SextoCajita)
                                            .addComponent(TerceroCajita)
                                            .addComponent(BachCajita))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AñadirDiccionarioBoton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(IsbnCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TituloCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(AutorCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(EditorialCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(PrimariaCajita)
                    .addComponent(EsoCajita)
                    .addComponent(BachCajita))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PrimeroCajita)
                    .addComponent(SegundoCajita)
                    .addComponent(TerceroCajita))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CuartoCajita)
                    .addComponent(QuintoCajita)
                    .addComponent(SextoCajita))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(MateriaCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(PrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PrecioConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AñadirDiccionarioBoton)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel6))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AñadirDiccionarioBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñadirDiccionarioBotonActionPerformed
        // TODO add your handling code here:
        
        Date date = new Date();
        double valor1 = PrecioVenta.getValue();
        double valor2 = PrecioConsulta.getValue();
        String nivel=null;
        
        int curso=1;
        if (BachCajita.isSelected()){
        nivel="Bachillerato";
        }
        else if (EsoCajita.isSelected()){
        nivel="ESO";
        }
        else if (PrimariaCajita.isSelected()){
        nivel="Primaria";
        }
        if (PrimeroCajita.isSelected()){
        curso=1;
        
        }
        else if (SegundoCajita.isSelected()){
        curso=2;
        
        }
        else if (TerceroCajita.isSelected()){
        curso=3;
        
        }
        else if (CuartoCajita.isSelected()){
        curso=4;
        
        }
        else if (QuintoCajita.isSelected()){
        curso=5;
        
        }
        else if (SextoCajita.isSelected()){
        curso=6;
        
        }
         
        LibroTexto texto = new LibroTexto(nivel, MateriaCampo.getText(),curso, IsbnCampo.getText(), TituloCampo.getText(),AutorCampo.getText(), EditorialCampo.getText(), date.getTime(), valor1,valor2);
        
        
        
     
        this.parent.getGestor().añadirLibroTexto(texto);
        
        JOptionPane.showMessageDialog(null, " \n Producto añadido con exito.", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);
        
        AñadirProductos e = new AñadirProductos(parent);
        e.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_AñadirDiccionarioBotonActionPerformed

    private void SegundoCajitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SegundoCajitaActionPerformed
        // TODO add your handling code here:
        SegundoCajita.setEnabled(false);

        PrimeroCajita.setSelected(false);
        TerceroCajita.setSelected(false);
        CuartoCajita.setSelected(false);
        QuintoCajita.setSelected(false);
        SextoCajita.setSelected(false);
        if (PrimariaCajita.isSelected()) {

            PrimeroCajita.setEnabled(true);
            TerceroCajita.setEnabled(true);
            CuartoCajita.setEnabled(true);
            QuintoCajita.setEnabled(true);
            SextoCajita.setEnabled(true);

        }
        if (EsoCajita.isSelected()) {

            PrimeroCajita.setEnabled(true);
            TerceroCajita.setEnabled(true);
            CuartoCajita.setEnabled(true);
            QuintoCajita.setEnabled(false);
            SextoCajita.setEnabled(false);

        }
        if (BachCajita.isSelected()) {
        
        PrimeroCajita.setEnabled(true);
            TerceroCajita.setEnabled(false);
            CuartoCajita.setEnabled(false);
            QuintoCajita.setEnabled(false);
            SextoCajita.setEnabled(false);
        
        }

    }//GEN-LAST:event_SegundoCajitaActionPerformed

    private void BachCajitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BachCajitaActionPerformed
        // TODO add your handling code here:
        PrimariaCajita.setEnabled(true);
        PrimariaCajita.setSelected(false);
        EsoCajita.setEnabled(true);
        EsoCajita.setSelected(false);
        BachCajita.setEnabled(false);

        PrimeroCajita.setSelected(true);
        PrimeroCajita.setEnabled(false);
        SegundoCajita.setSelected(false);
        SegundoCajita.setEnabled(true);
        TerceroCajita.setSelected(false);
        TerceroCajita.setEnabled(false);
        CuartoCajita.setSelected(false);
        CuartoCajita.setEnabled(false);
        QuintoCajita.setSelected(false);
        QuintoCajita.setEnabled(false);
        SextoCajita.setSelected(false);
        SextoCajita.setEnabled(false);
    }//GEN-LAST:event_BachCajitaActionPerformed

    private void EsoCajitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EsoCajitaActionPerformed
        // TODO add your handling code here:
        PrimariaCajita.setEnabled(true);
        PrimariaCajita.setSelected(false);
        BachCajita.setEnabled(true);
        BachCajita.setSelected(false);
        EsoCajita.setEnabled(false);

        PrimeroCajita.setSelected(true);
        PrimeroCajita.setEnabled(false);
        SegundoCajita.setSelected(false);
        SegundoCajita.setEnabled(true);
        TerceroCajita.setSelected(false);
        TerceroCajita.setEnabled(true);
        CuartoCajita.setSelected(false);
        CuartoCajita.setEnabled(true);
        QuintoCajita.setSelected(false);
        QuintoCajita.setEnabled(false);
        SextoCajita.setSelected(false);
        SextoCajita.setEnabled(false);
    }//GEN-LAST:event_EsoCajitaActionPerformed

    private void PrimariaCajitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrimariaCajitaActionPerformed
        // TODO add your handling code here:
        EsoCajita.setEnabled(true);
        EsoCajita.setSelected(false);
        BachCajita.setEnabled(true);
        BachCajita.setSelected(false);
        PrimariaCajita.setEnabled(false);

        PrimeroCajita.setSelected(true);
        PrimeroCajita.setEnabled(false);
        SegundoCajita.setSelected(false);
        SegundoCajita.setEnabled(true);
        TerceroCajita.setSelected(false);
        TerceroCajita.setEnabled(true);
        CuartoCajita.setSelected(false);
        CuartoCajita.setEnabled(true);
        QuintoCajita.setSelected(false);
        QuintoCajita.setEnabled(true);
        SextoCajita.setSelected(false);
        SextoCajita.setEnabled(true);
    }//GEN-LAST:event_PrimariaCajitaActionPerformed

    private void PrimeroCajitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrimeroCajitaActionPerformed
        // TODO add your handling code here:
        PrimeroCajita.setEnabled(false);

        SegundoCajita.setSelected(false);
        TerceroCajita.setSelected(false);
        CuartoCajita.setSelected(false);
        QuintoCajita.setSelected(false);
        SextoCajita.setSelected(false);
        if (PrimariaCajita.isSelected()) {

            SegundoCajita.setEnabled(true);
            TerceroCajita.setEnabled(true);
            CuartoCajita.setEnabled(true);
            QuintoCajita.setEnabled(true);
            SextoCajita.setEnabled(true);

        }
        if (EsoCajita.isSelected()) {
            SegundoCajita.setEnabled(true);
            TerceroCajita.setEnabled(true);
            CuartoCajita.setEnabled(true);
            QuintoCajita.setEnabled(false);
            SextoCajita.setEnabled(false);

        }
        if (BachCajita.isSelected()) {
        
            SegundoCajita.setEnabled(true);
            TerceroCajita.setEnabled(false);
            CuartoCajita.setEnabled(false);
            QuintoCajita.setEnabled(false);
            SextoCajita.setEnabled(false);
            
        }


    }//GEN-LAST:event_PrimeroCajitaActionPerformed

    private void TerceroCajitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TerceroCajitaActionPerformed
        // TODO add your handling code here:
        TerceroCajita.setEnabled(false);

        PrimeroCajita.setSelected(false);
        SegundoCajita.setSelected(false);
        CuartoCajita.setSelected(false);
        QuintoCajita.setSelected(false);
        SextoCajita.setSelected(false);
        if (PrimariaCajita.isSelected()) {

            PrimeroCajita.setEnabled(true);
            SegundoCajita.setEnabled(true);
            CuartoCajita.setEnabled(true);
            QuintoCajita.setEnabled(true);
            SextoCajita.setEnabled(true);

        }
        if (EsoCajita.isSelected()) {
        
        
         PrimeroCajita.setEnabled(true);
            SegundoCajita.setEnabled(true);
            CuartoCajita.setEnabled(true);
            QuintoCajita.setEnabled(false);
            SextoCajita.setEnabled(false);
        }
    }//GEN-LAST:event_TerceroCajitaActionPerformed

    private void CuartoCajitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuartoCajitaActionPerformed
        // TODO add your handling code here:
        CuartoCajita.setEnabled(false);

        PrimeroCajita.setSelected(false);
        SegundoCajita.setSelected(false);
        TerceroCajita.setSelected(false);
        QuintoCajita.setSelected(false);
        SextoCajita.setSelected(false);
        if (PrimariaCajita.isSelected()) {

            PrimeroCajita.setEnabled(true);
            SegundoCajita.setEnabled(true);
            TerceroCajita.setEnabled(true);
            QuintoCajita.setEnabled(true);
            SextoCajita.setEnabled(true);

        }
        if (EsoCajita.isSelected()) {
        
         PrimeroCajita.setEnabled(true);
            SegundoCajita.setEnabled(true);
            TerceroCajita.setEnabled(true);
            QuintoCajita.setEnabled(false);
            SextoCajita.setEnabled(false);
        }
    }//GEN-LAST:event_CuartoCajitaActionPerformed

    private void QuintoCajitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuintoCajitaActionPerformed
        // TODO add your handling code here:
        QuintoCajita.setEnabled(false);

        PrimeroCajita.setSelected(false);
        SegundoCajita.setSelected(false);
        TerceroCajita.setSelected(false);
        CuartoCajita.setSelected(false);
        SextoCajita.setSelected(false);
        if (PrimariaCajita.isSelected()) {

            PrimeroCajita.setEnabled(true);
            SegundoCajita.setEnabled(true);
            TerceroCajita.setEnabled(true);
            CuartoCajita.setEnabled(true);
            SextoCajita.setEnabled(true);

        }
    }//GEN-LAST:event_QuintoCajitaActionPerformed

    private void SextoCajitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SextoCajitaActionPerformed
        // TODO add your handling code here:
        SextoCajita.setEnabled(false);

        PrimeroCajita.setSelected(false);
        SegundoCajita.setSelected(false);
        TerceroCajita.setSelected(false);
        CuartoCajita.setSelected(false);
        QuintoCajita.setSelected(false);
        if (PrimariaCajita.isSelected()) {

            PrimeroCajita.setEnabled(true);
            SegundoCajita.setEnabled(true);
            TerceroCajita.setEnabled(true);
            CuartoCajita.setEnabled(true);
            QuintoCajita.setEnabled(true);

        }
    }//GEN-LAST:event_SextoCajitaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        AñadirProductos alta = new AñadirProductos(this.parent);
        this.setVisible(false);
        alta.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AutorCampo;
    private javax.swing.JButton AñadirDiccionarioBoton;
    private javax.swing.JCheckBox BachCajita;
    private javax.swing.JRadioButton CuartoCajita;
    private javax.swing.JTextField EditorialCampo;
    private javax.swing.JCheckBox EsoCajita;
    private javax.swing.JTextField IsbnCampo;
    private javax.swing.JTextField MateriaCampo;
    private javax.swing.JSlider PrecioConsulta;
    private javax.swing.JSlider PrecioVenta;
    private javax.swing.JCheckBox PrimariaCajita;
    private javax.swing.JRadioButton PrimeroCajita;
    private javax.swing.JRadioButton QuintoCajita;
    private javax.swing.JRadioButton SegundoCajita;
    private javax.swing.JRadioButton SextoCajita;
    private javax.swing.JRadioButton TerceroCajita;
    private javax.swing.JTextField TituloCampo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
