
public class Busqueda extends javax.swing.JFrame {

    /**
     * Creates new form Busqueda
     */
    private VentanaBienvenida parent;

    public Busqueda(VentanaBienvenida ett) {
        initComponents();
        PrimeroCajita.setSelected(true);
        PrimeroCajita.setEnabled(false);
        
        parent = ett;
        parent.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator3 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        IdiomaCaja = new javax.swing.JTextField();
        MateriaCursoBoton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        MateriaCaja = new javax.swing.JTextField();
        IdiomaBusqBoton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        MarcaCaja = new javax.swing.JTextField();
        MarcaBusqBoton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        IsbnCaja = new javax.swing.JTextField();
        IsbnBuscarBoton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        AutorCaja = new javax.swing.JTextField();
        TituloCaja = new javax.swing.JTextField();
        AutorTitBuscBoton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        AutorSoloCaja = new javax.swing.JTextField();
        TituloSoloCaja = new javax.swing.JTextField();
        AutorBuscarBoton = new javax.swing.JButton();
        TituloBuscarBoton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ResultadoBusqueda = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        IsbnCompraCaja = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        ComprarBoton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        PrecioSlider = new javax.swing.JSlider();
        PrecioBuscarBoton = new javax.swing.JButton();
        jSeparator11 = new javax.swing.JSeparator();
        ConsultarBoton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        NumSerieCompra = new javax.swing.JTextField();
        ComprarLectorBoton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        PrimeroCajita = new javax.swing.JCheckBox();
        SegundoCajita = new javax.swing.JCheckBox();
        CuartoCajita = new javax.swing.JCheckBox();
        QuintoCajita = new javax.swing.JCheckBox();
        SextoCajita = new javax.swing.JCheckBox();
        TerceroCajita = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LIBRERIA DIGITAL");

        jLabel1.setText("Busqueda Simple");

        jLabel2.setText("Busqueda Avanzada");

        jLabel3.setText("Libros de texto:     Materia:");

        jLabel4.setText("Curso:");

        IdiomaCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdiomaCajaActionPerformed(evt);
            }
        });

        MateriaCursoBoton.setText("Buscar");
        MateriaCursoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MateriaCursoBotonActionPerformed(evt);
            }
        });

        jLabel5.setText("Diccionarios:           Idioma:");

        MateriaCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MateriaCajaActionPerformed(evt);
            }
        });

        IdiomaBusqBoton.setText("Buscar");
        IdiomaBusqBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdiomaBusqBotonActionPerformed(evt);
            }
        });

        jLabel6.setText("Lectores:                Marca:");

        MarcaCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarcaCajaActionPerformed(evt);
            }
        });

        MarcaBusqBoton.setText("Buscar");
        MarcaBusqBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarcaBusqBotonActionPerformed(evt);
            }
        });

        jLabel7.setText("ISBN:");

        IsbnBuscarBoton.setText("Buscar");
        IsbnBuscarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IsbnBuscarBotonActionPerformed(evt);
            }
        });

        jLabel8.setText("Autor:");

        TituloCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TituloCajaActionPerformed(evt);
            }
        });

        AutorTitBuscBoton.setText("Buscar");
        AutorTitBuscBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AutorTitBuscBotonActionPerformed(evt);
            }
        });

        jLabel9.setText("Autor:");

        jLabel10.setText("Título:");

        AutorBuscarBoton.setText("Buscar");
        AutorBuscarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AutorBuscarBotonActionPerformed(evt);
            }
        });

        TituloBuscarBoton.setText("Buscar");
        TituloBuscarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TituloBuscarBotonActionPerformed(evt);
            }
        });

        jSeparator9.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator9.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ResultadoBusqueda.setColumns(20);
        ResultadoBusqueda.setRows(5);
        jScrollPane1.setViewportView(ResultadoBusqueda);

        jLabel11.setText("Introduzca el ISBN del libro que desea comprar o consultar online:");

        ComprarBoton.setText("Comprar");
        ComprarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComprarBotonActionPerformed(evt);
            }
        });

        jLabel12.setText("Precio:");

        PrecioSlider.setMajorTickSpacing(25);
        PrecioSlider.setMaximum(500);
        PrecioSlider.setPaintLabels(true);
        PrecioSlider.setPaintTicks(true);

        PrecioBuscarBoton.setText("Buscar");
        PrecioBuscarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecioBuscarBotonActionPerformed(evt);
            }
        });

        ConsultarBoton.setText("Consultar");
        ConsultarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarBotonActionPerformed(evt);
            }
        });

        jLabel13.setText("Introduzca el Numero de serie del Lector que desea comprar:");

        ComprarLectorBoton.setText("Comprar");
        ComprarLectorBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComprarLectorBotonActionPerformed(evt);
            }
        });

        jButton2.setText("Ver todo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        PrimeroCajita.setText("1º");
        PrimeroCajita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrimeroCajitaActionPerformed(evt);
            }
        });

        SegundoCajita.setText("2º");
        SegundoCajita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SegundoCajitaActionPerformed(evt);
            }
        });

        CuartoCajita.setText("4º");
        CuartoCajita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuartoCajitaActionPerformed(evt);
            }
        });

        QuintoCajita.setText("5º");
        QuintoCajita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuintoCajitaActionPerformed(evt);
            }
        });

        SextoCajita.setText("6º");
        SextoCajita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SextoCajitaActionPerformed(evt);
            }
        });

        TerceroCajita.setText("3º");
        TerceroCajita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TerceroCajitaActionPerformed(evt);
            }
        });

        jLabel14.setText("y Titulo:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("REALIZAR COMPRA DEL PRODUCTO:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(94, 94, 94)
                                                .addComponent(jLabel4))
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(IdiomaCaja)
                                        .addComponent(MarcaCaja, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(PrimeroCajita)
                                        .addGap(3, 3, 3)
                                        .addComponent(SegundoCajita)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TerceroCajita))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(MateriaCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(CuartoCajita)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(QuintoCajita)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SextoCajita)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(MarcaBusqBoton)
                                        .addGap(20, 20, 20))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(MateriaCursoBoton)
                                        .addGap(28, 28, 28))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(IdiomaBusqBoton)
                                        .addGap(30, 30, 30))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PrecioSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jSeparator11, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel12))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(IsbnCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(IsbnBuscarBoton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(AutorSoloCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(AutorBuscarBoton))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(TituloSoloCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TituloBuscarBoton))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel8)
                        .addGap(6, 6, 6)
                        .addComponent(AutorCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TituloCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AutorTitBuscBoton))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator10)
                            .addComponent(jSeparator2)
                            .addComponent(jSeparator9)
                            .addComponent(jSeparator7)
                            .addComponent(jSeparator5)
                            .addComponent(jSeparator4)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PrecioBuscarBoton)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(IsbnCompraCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ComprarBoton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ConsultarBoton))
                            .addComponent(jLabel11)
                            .addComponent(jLabel13)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NumSerieCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ComprarLectorBoton)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IsbnCompraCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComprarBoton)
                            .addComponent(ConsultarBoton))
                        .addGap(66, 66, 66))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(78, 78, 78)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel4)
                                            .addComponent(PrimeroCajita)
                                            .addComponent(SegundoCajita)
                                            .addComponent(CuartoCajita)
                                            .addComponent(TerceroCajita)
                                            .addComponent(QuintoCajita)
                                            .addComponent(SextoCajita))
                                        .addGap(20, 20, 20))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(MateriaCursoBoton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(IdiomaCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(IdiomaBusqBoton))
                                .addGap(3, 3, 3)
                                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(MarcaCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MarcaBusqBoton))
                                .addGap(7, 7, 7)
                                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(IsbnCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(IsbnBuscarBoton)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(MateriaCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addGap(27, 27, 27)
                        .addComponent(PrecioSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PrecioBuscarBoton)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(AutorSoloCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AutorBuscarBoton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(TituloSoloCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TituloBuscarBoton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(AutorCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TituloCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AutorTitBuscBoton)
                            .addComponent(jLabel14))
                        .addGap(74, 74, 74))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NumSerieCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComprarLectorBoton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addContainerGap())))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void IdiomaCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdiomaCajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdiomaCajaActionPerformed

    private void MateriaCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MateriaCajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MateriaCajaActionPerformed

    private void MarcaCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarcaCajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MarcaCajaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        VentanaCliente prog = new VentanaCliente(this.parent);
        this.setVisible(false);
        prog.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TituloCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TituloCajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TituloCajaActionPerformed

    private void MateriaCursoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MateriaCursoBotonActionPerformed
        // TODO add your handling code here:
        ComprarLectorBoton.setEnabled(false);
        ComprarBoton.setEnabled(true);
        ConsultarBoton.setEnabled(true);
        int curso=1;
        if (PrimeroCajita.isSelected()){
        curso=1;
        }else if (SegundoCajita.isSelected()){
        curso=2;
        }else if (TerceroCajita.isSelected()){
        curso=3;
        }else if (CuartoCajita.isSelected()){
        curso=4;
        }else if (QuintoCajita.isSelected()){
        curso=5;
        }else if (SextoCajita.isSelected()){
        curso=6;
        }
        
        if (MateriaCaja.getText().equals("") ) {
            ResultadoBusqueda.setText("Por favor, introduzca los parámetros correctamente.");

        } else {
            
            ResultadoBusqueda.setText(this.parent.getGestor().busquedaMateriaCurso(MateriaCaja.getText(), curso));
        }

    }//GEN-LAST:event_MateriaCursoBotonActionPerformed

    private void IdiomaBusqBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdiomaBusqBotonActionPerformed
        // TODO add your handling code here:
        ComprarLectorBoton.setEnabled(false);
        ComprarBoton.setEnabled(true);
        ConsultarBoton.setEnabled(true);
        if (IdiomaCaja.getText().equals("")) {
            ResultadoBusqueda.setText("Por favor, introduzca los parámetros correctamente.");

        } else {
            ResultadoBusqueda.setText(this.parent.getGestor().busquedaDiccIdioma(IdiomaCaja.getText()));
        }
    }//GEN-LAST:event_IdiomaBusqBotonActionPerformed

    private void MarcaBusqBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarcaBusqBotonActionPerformed
        // TODO add your handling code here:
        ComprarLectorBoton.setEnabled(true);
        ComprarBoton.setEnabled(false);
        ConsultarBoton.setEnabled(false);
        if (MarcaCaja.getText().equals("")) {
            ResultadoBusqueda.setText("Por favor, introduzca los parámetros correctamente.");

        } else {
            ResultadoBusqueda.setText(this.parent.getGestor().busquedaLectoresMarca(MarcaCaja.getText()));
        }
    }//GEN-LAST:event_MarcaBusqBotonActionPerformed

    private void IsbnBuscarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IsbnBuscarBotonActionPerformed
        // TODO add your handling code here:
        ComprarLectorBoton.setEnabled(false);
        ComprarBoton.setEnabled(true);
        ConsultarBoton.setEnabled(true);
        ResultadoBusqueda.setText(this.parent.getGestor().busquedaAvIsbn(IsbnCaja.getText()));
    }//GEN-LAST:event_IsbnBuscarBotonActionPerformed

    private void PrecioBuscarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecioBuscarBotonActionPerformed
        // TODO add your handling code here:
        ComprarLectorBoton.setEnabled(true);
        ComprarBoton.setEnabled(false);
        ConsultarBoton.setEnabled(false);
        int i = PrecioSlider.getValue();
        double d = (double) i;
        Lector[] nuevo = this.parent.getGestor().busquedaAvPrecio(d);
       // for (int j = 0; j < nuevo.length; j++) {               
        //     ResultadoBusqueda.setText(nuevo[j].toStringA());

        // }
        int j = 0;
        while (j < nuevo.length) {
            ResultadoBusqueda.setText(nuevo[j].toStringA());
            j++;
        }
    }//GEN-LAST:event_PrecioBuscarBotonActionPerformed

    private void AutorBuscarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AutorBuscarBotonActionPerformed
        // TODO add your handling code here:
        ComprarLectorBoton.setEnabled(false);
        ComprarBoton.setEnabled(true);
        ConsultarBoton.setEnabled(true);
        if (AutorSoloCaja.getText().equals("")) {
            ResultadoBusqueda.setText("Por favor, introduzca los parámetros correctamente.");

        } else {
            ResultadoBusqueda.setText(this.parent.getGestor().busquedaAvanzadaAutor(AutorSoloCaja.getText()));
        }
    }//GEN-LAST:event_AutorBuscarBotonActionPerformed

    private void TituloBuscarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TituloBuscarBotonActionPerformed
        // TODO add your handling code here:
        ComprarLectorBoton.setEnabled(false);
        ComprarBoton.setEnabled(true);
        ConsultarBoton.setEnabled(true);
        if (TituloSoloCaja.getText().equals("")) {
            ResultadoBusqueda.setText("Por favor, introduzca los parámetros correctamente.");

        } else {
            ResultadoBusqueda.setText(this.parent.getGestor().busquedaAvanzadaTitulo(TituloSoloCaja.getText()));
        }
    }//GEN-LAST:event_TituloBuscarBotonActionPerformed

    private void AutorTitBuscBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AutorTitBuscBotonActionPerformed
        // TODO add your handling code here:
        ComprarLectorBoton.setEnabled(false);
        ComprarBoton.setEnabled(true);
        ConsultarBoton.setEnabled(true);
        if (TituloCaja.getText().equals("") || AutorCaja.getText().equals("")) {
            ResultadoBusqueda.setText("Por favor, introduzca los parámetros correctamente.");

        } else {
            ResultadoBusqueda.setText(this.parent.getGestor().busquedaAvanzada(AutorCaja.getText(), TituloCaja.getText()));
        }
    }//GEN-LAST:event_AutorTitBuscBotonActionPerformed

    private void ComprarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComprarBotonActionPerformed
        // TODO add your handling code here:
        String Isbn = IsbnCompraCaja.getText();
        if (Isbn.equals("")) {

            ResultadoBusqueda.setText("Por favor, introduzca los parámetros correctamente.");

        } else {

            if (this.parent.getGestor().containsTexto(Isbn) || this.parent.getGestor().containsLectura(Isbn) || this.parent.getGestor().containsDicc(Isbn)) {

                String Isbn2 = IsbnCompraCaja.getText();
                this.parent.getGestor().ComprarLibro(Isbn2);
                ComprarPublicacionDigital compra = new ComprarPublicacionDigital(this.parent);
                this.setVisible(false);
                compra.setVisible(true);

            } else {
                ResultadoBusqueda.setText("No se han encontrado coincidencias");
            }
        }
    }//GEN-LAST:event_ComprarBotonActionPerformed

    private void ConsultarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarBotonActionPerformed
        // TODO add your handling code here:
         
        String Isbn = IsbnCompraCaja.getText();
        if (Isbn.equals("")) {

            ResultadoBusqueda.setText("Por favor, introduzca los parámetros correctamente.");

        } else {

            if (this.parent.getGestor().containsTexto(Isbn) || this.parent.getGestor().containsLectura(Isbn) || this.parent.getGestor().containsDicc(Isbn)) {

                
                this.parent.getGestor().ComprarLibro(Isbn);
                ComprarPublicacionDigitalPorConsulta consulta = new ComprarPublicacionDigitalPorConsulta(this.parent);
                this.setVisible(false);
                consulta.setVisible(true);

            } else {
                ResultadoBusqueda.setText("No se han encontrado coincidencias");
            }
        }


    }//GEN-LAST:event_ConsultarBotonActionPerformed

    private void ComprarLectorBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComprarLectorBotonActionPerformed
        // TODO add your handling code here:
        String numero = NumSerieCompra.getText();
        if (numero.equals("")) {

            ResultadoBusqueda.setText("Por favor, introduzca los parámetros correctamente.");

        } else {

            if (this.parent.getGestor().containsLector(numero)) {

                String lector = NumSerieCompra.getText();
                this.parent.getGestor().ComprarLector(lector);

                ComprarLector compra = new ComprarLector(this.parent);
                this.setVisible(false);
                compra.setVisible(true);

            } else {
                ResultadoBusqueda.setText("No se han encontrado coincidencias");
            }
        }
    }//GEN-LAST:event_ComprarLectorBotonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ResultadoBusqueda.setText(this.parent.getGestor().verTodo());
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void PrimeroCajitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrimeroCajitaActionPerformed
        // TODO add your handling code here:
        SegundoCajita.setSelected(false);
        TerceroCajita.setSelected(false);
        CuartoCajita.setSelected(false);
        QuintoCajita.setSelected(false);
        SextoCajita.setSelected(false);
        
        
        PrimeroCajita.setEnabled(false);
        
        SegundoCajita.setEnabled(true);
        TerceroCajita.setEnabled(true);
        CuartoCajita.setEnabled(true);
        QuintoCajita.setEnabled(true);
        SextoCajita.setEnabled(true);
    }//GEN-LAST:event_PrimeroCajitaActionPerformed

    private void SegundoCajitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SegundoCajitaActionPerformed
        // TODO add your handling code here:
        PrimeroCajita.setSelected(false);
        TerceroCajita.setSelected(false);
        CuartoCajita.setSelected(false);
        QuintoCajita.setSelected(false);
        SextoCajita.setSelected(false);
        
        SegundoCajita.setEnabled(false);
        
        PrimeroCajita.setEnabled(true);
        TerceroCajita.setEnabled(true);
        CuartoCajita.setEnabled(true);
        QuintoCajita.setEnabled(true);
        SextoCajita.setEnabled(true);
    }//GEN-LAST:event_SegundoCajitaActionPerformed

    private void TerceroCajitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TerceroCajitaActionPerformed
        // TODO add your handling code here:
        PrimeroCajita.setSelected(false);
        SegundoCajita.setSelected(false);
        CuartoCajita.setSelected(false);
        QuintoCajita.setSelected(false);
        SextoCajita.setSelected(false);
        
        TerceroCajita.setEnabled(false);
        
        PrimeroCajita.setEnabled(true);
        SegundoCajita.setEnabled(true);
        CuartoCajita.setEnabled(true);
        QuintoCajita.setEnabled(true);
        SextoCajita.setEnabled(true);
    }//GEN-LAST:event_TerceroCajitaActionPerformed

    private void CuartoCajitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuartoCajitaActionPerformed
        // TODO add your handling code here:
        PrimeroCajita.setSelected(false);
        SegundoCajita.setSelected(false);
        TerceroCajita.setSelected(false);
        QuintoCajita.setSelected(false);
        SextoCajita.setSelected(false);
        
        CuartoCajita.setEnabled(false);
        
        PrimeroCajita.setEnabled(true);
        SegundoCajita.setEnabled(true);
        TerceroCajita.setEnabled(true);
        QuintoCajita.setEnabled(true);
        SextoCajita.setEnabled(true);
    }//GEN-LAST:event_CuartoCajitaActionPerformed

    private void QuintoCajitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuintoCajitaActionPerformed
        // TODO add your handling code here:
        PrimeroCajita.setSelected(false);
        SegundoCajita.setSelected(false);
        TerceroCajita.setSelected(false);
        CuartoCajita.setSelected(false);
        SextoCajita.setSelected(false);
        
        QuintoCajita.setEnabled(false);
        
        PrimeroCajita.setEnabled(true);
        SegundoCajita.setEnabled(true);
        TerceroCajita.setEnabled(true);
        CuartoCajita.setEnabled(true);
        SextoCajita.setEnabled(true);
    }//GEN-LAST:event_QuintoCajitaActionPerformed

    private void SextoCajitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SextoCajitaActionPerformed
        // TODO add your handling code here:
        PrimeroCajita.setSelected(false);
        SegundoCajita.setSelected(false);
        TerceroCajita.setSelected(false);
        CuartoCajita.setSelected(false);
        QuintoCajita.setSelected(false);
        
        SextoCajita.setEnabled(false);
        
        PrimeroCajita.setEnabled(true);
        SegundoCajita.setEnabled(true);
        TerceroCajita.setEnabled(true);
        CuartoCajita.setEnabled(true);
        QuintoCajita.setEnabled(true);
    }//GEN-LAST:event_SextoCajitaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AutorBuscarBoton;
    private javax.swing.JTextField AutorCaja;
    private javax.swing.JTextField AutorSoloCaja;
    private javax.swing.JButton AutorTitBuscBoton;
    private javax.swing.JButton ComprarBoton;
    private javax.swing.JButton ComprarLectorBoton;
    private javax.swing.JButton ConsultarBoton;
    private javax.swing.JCheckBox CuartoCajita;
    private javax.swing.JButton IdiomaBusqBoton;
    private javax.swing.JTextField IdiomaCaja;
    private javax.swing.JButton IsbnBuscarBoton;
    private javax.swing.JTextField IsbnCaja;
    private javax.swing.JTextField IsbnCompraCaja;
    private javax.swing.JButton MarcaBusqBoton;
    private javax.swing.JTextField MarcaCaja;
    private javax.swing.JTextField MateriaCaja;
    private javax.swing.JButton MateriaCursoBoton;
    private javax.swing.JTextField NumSerieCompra;
    private javax.swing.JButton PrecioBuscarBoton;
    private javax.swing.JSlider PrecioSlider;
    private javax.swing.JCheckBox PrimeroCajita;
    private javax.swing.JCheckBox QuintoCajita;
    private javax.swing.JTextArea ResultadoBusqueda;
    private javax.swing.JCheckBox SegundoCajita;
    private javax.swing.JCheckBox SextoCajita;
    private javax.swing.JCheckBox TerceroCajita;
    private javax.swing.JButton TituloBuscarBoton;
    private javax.swing.JTextField TituloCaja;
    private javax.swing.JTextField TituloSoloCaja;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    // End of variables declaration//GEN-END:variables
}
