
import javax.swing.JOptionPane;


public class LogAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form LogAdministrador
     */
    private VentanaBienvenida parent;
    public LogAdministrador(VentanaBienvenida ett) {
        initComponents();
        parent = ett;
        parent.setVisible(false);
    }

       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IniciarSesionBoton = new javax.swing.JButton();
        UsuarioLabel = new javax.swing.JLabel();
        ContraseñaLabel = new javax.swing.JLabel();
        EscribirUsuario = new javax.swing.JTextField();
        EscribirContraseña = new javax.swing.JTextField();
        AtrasBoton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LIBRERIA DIGITAL");

        IniciarSesionBoton.setText("Iniciar Sesion");
        IniciarSesionBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarSesionBotonActionPerformed(evt);
            }
        });

        UsuarioLabel.setText("Usuario:");

        ContraseñaLabel.setText("Contraseña:");

        EscribirContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EscribirContraseñaActionPerformed(evt);
            }
        });

        AtrasBoton.setText("Atrás");
        AtrasBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasBotonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Iniciar sesion como administrador:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ContraseñaLabel)
                            .addComponent(UsuarioLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EscribirUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EscribirContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(65, 65, 65))
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(IniciarSesionBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AtrasBoton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsuarioLabel)
                    .addComponent(EscribirUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ContraseñaLabel)
                    .addComponent(EscribirContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IniciarSesionBoton)
                    .addComponent(AtrasBoton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void EscribirContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EscribirContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EscribirContraseñaActionPerformed

    private void AtrasBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasBotonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        parent.setVisible(true);
    }//GEN-LAST:event_AtrasBotonActionPerformed

    private void IniciarSesionBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarSesionBotonActionPerformed
        // TODO add your handling code here:
         
        if(EscribirUsuario.getText().equals("admin") && EscribirContraseña.getText().equals("admin")){
            VentanaAdmin adminprog = new VentanaAdmin(this.parent);
            adminprog.setVisible(true);
            this.setVisible(false);
            
        
        
        }else{
           JOptionPane.showMessageDialog(null, " \n Contraseña incorrecta.", "ERROR", JOptionPane.ERROR_MESSAGE);
        LogAdministrador e = new LogAdministrador(parent);
        e.setVisible(true);
        this.setVisible(false);
        
        }
    }//GEN-LAST:event_IniciarSesionBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AtrasBoton;
    private javax.swing.JLabel ContraseñaLabel;
    private javax.swing.JTextField EscribirContraseña;
    private javax.swing.JTextField EscribirUsuario;
    private javax.swing.JButton IniciarSesionBoton;
    private javax.swing.JLabel UsuarioLabel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
