# Project: Abaco_PL2
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = main.o Abaco.o Pila.o Lista.o Bolita.o NodoLista.o NodoPila.o Arbol.o NodoArbol.o table_printer.o
LINKOBJ  = main.o Abaco.o Pila.o Lista.o Bolita.o NodoLista.o NodoPila.o Arbol.o NodoArbol.o table_printer.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Abaco_PL2.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

Abaco.o: Abaco.cpp
	$(CPP) -c Abaco.cpp -o Abaco.o $(CXXFLAGS)

Pila.o: Pila.cpp
	$(CPP) -c Pila.cpp -o Pila.o $(CXXFLAGS)

Lista.o: Lista.cpp
	$(CPP) -c Lista.cpp -o Lista.o $(CXXFLAGS)

Bolita.o: Bolita.cpp
	$(CPP) -c Bolita.cpp -o Bolita.o $(CXXFLAGS)

NodoLista.o: NodoLista.cpp
	$(CPP) -c NodoLista.cpp -o NodoLista.o $(CXXFLAGS)

NodoPila.o: NodoPila.cpp
	$(CPP) -c NodoPila.cpp -o NodoPila.o $(CXXFLAGS)

Arbol.o: Arbol.cpp
	$(CPP) -c Arbol.cpp -o Arbol.o $(CXXFLAGS)

NodoArbol.o: NodoArbol.cpp
	$(CPP) -c NodoArbol.cpp -o NodoArbol.o $(CXXFLAGS)

table_printer.o: table_printer.cpp
	$(CPP) -c table_printer.cpp -o table_printer.o $(CXXFLAGS)
